### ISSUE TITLE
No need to wait after Wire.requestFrom(). No need to remove garbage.

### ISSUE THREAD

**Issue by Koepel** [NiryoRobotics/niryo_stepper#1]
In the file "AS5600.cpp", in the function "read_encoder()" there is a while-loop after the Wire.requestFrom(), but there is nothing to wait for. When the Wire.requestFrom() returns, the I2C transaction has completely finished and the received bytes are waiting in a buffer in the Wire library.

You can remove this line:
```
while (Wire.available() < 2);
```

You may remove these lines as well:
```
while(Wire.available()) {
    Wire.read(); // garbage
}
```
When 2 bytes are requested, it is impossible to get more than 2 bytes. Even when those two bytes are not read, there is no need to remove any garbage, because the buffers are cleared when a new I2C transaction starts.

**Comment by renarded** [comment]
Hi, 

Thanks for the info!

This has been fixed [here](https://github.com/NiryoRobotics/niryo_stepper/commit/d9488fed80b30b93ae9e238983448c91bcf15abb).

For curious people --> reference code of Wire library for SAMD [here]( https://github.com/arduino/ArduinoCore-samd/blob/master/libraries/Wire/Wire.cpp )
