### ISSUE TITLE
How to build the Niryo Stepper ?

### ISSUE THREAD

**Issue by ppedro74** [NiryoRobotics/niryo_stepper#2]
Hi,

Where can i find the:
1) Niryo stepper custom pcb  schematic ?
2) Niryo stepper custom pcb BOM ?
3) Niryo stepper motor supplier reference for each stepper ?

Thank you

**Comment by renarded** [comment]
Hi,
We haven't released the PCB BOM nor the complete schematics. Though you can get an overview of the schematics [here](https://github.com/NiryoRobotics/niryo_one/blob/master/Electronics/Niryo_stepper_overview.pdf).
For NiryoSteppers we use NEMA 17 motors. Those motors are only sold with the [Niryo One robot](https://niryo.com/niryo-one/).
